#!/usr/bin/env bash
sudo mount -t cifs //192.168.2.62/algorand /media/NAS -o user=wwinder,uid=1000,gid=1000
sudo mount -t cifs //192.168.2.62/Important /media/NAS_IMPORTANT -o user=wwinder,uid=1000,gid=1000
